In [1]:
import numpy as np

In [2]:
# create a array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
#numpy.ndarray  nd means n dimension data menas we can create 1d, 2d 100d data.

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
np.array([1,2,3,4,5,"sachin",4+8j])

array(['1', '2', '3', '4', '5', 'sachin', '(4+8j)'], dtype='<U64')

In [8]:
np.array([1,3,4,5.8,6.8])

array([1. , 3. , 4. , 5.8, 6.8])

In [9]:
np.array([1.2,2.5,7,8]) # 1 dimensional arrary because it started wiht ([)

array([1.2, 2.5, 7. , 8. ])

In [10]:
np.array([1.2,2.5,7,8,"sachin"]) # it's known as upcasting,  It would be convert the data type based on size of datatype

array(['1.2', '2.5', '7', '8', 'sachin'], dtype='<U32')

In [11]:
np.array([[1,3],[3,5]])

array([[1, 3],
       [3, 5]])

In [1]:
np.array([[1,3],[3,5],[5,7]]) # 2 dimensional arrary because it started wiht ([[)

NameError: name 'np' is not defined

In [ ]:
np.array([[1,3],[3,5],[5,7],[7,9,11]])
# Get the following wranning because, all the array doesn't contain same data element's in each array,
# So that's why insteading array, it will create a list

In [ ]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]]) # 3 dimensional arrary because it started wiht ([[[)

In [ ]:
np.array([1,2,4] , ndmin=3) # 3 dimensional array

In [ ]:
np.array([1,2,3], dtype= complex) # Type casting

In [ ]:
np.array([1,2,3], dtype= str) # Type casting

In [ ]:
np.array([(1,2),(4,5)]) # you can create array by list[] or tuple()

In [ ]:
np.array([[1,2],[4,5]])

In [ ]:
arr = np.array([(1,2), (4,5)],dtype=[("a", '<i2'),("b",'<i8')])

In [ ]:
arr

In [ ]:
arr[0]

In [13]:
arr[0][0]

NameError: name 'arr' is not defined

In [ ]:
type(arr[0][0])

In [ ]:
arr[0][1]

In [ ]:
type(arr[0][1])

In [ ]:
"""
<i2 = int16
<i4 = int32
<i8 = int64
"""

In [14]:
arr = np.array([[1,3],[3,5]])

In [15]:
arr[0][1]

3

In [16]:
type(arr[0][1])

numpy.int32

In [17]:
# We can find follwoing two types of data types in numpy
# array
# matrix

In [18]:
np.mat(arr)

matrix([[1, 3],
        [3, 5]])

In [19]:
np.matrix(arr)

matrix([[1, 3],
        [3, 5]])

In [20]:
# Using multple way we can covert list to array

In [21]:
l = [2,5,6,89,10]

In [22]:
np.array(l)

array([ 2,  5,  6, 89, 10])

In [23]:
np.asarray(l)

array([ 2,  5,  6, 89, 10])

In [24]:
np.asanyarray(l)

array([ 2,  5,  6, 89, 10])

In [25]:
mat=np.mat(arr)

In [26]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 5]])

In [27]:
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [28]:
issubclass(np.matrix,np.ndarray)

True

In [29]:
issubclass(np.ndarray,np.matrix)

False

In [30]:
arr

array([[1, 3],
       [3, 5]])

In [31]:
a = arr # shallow(solo) copy

In [32]:
b = np.copy(arr) # Deep copy

In [33]:
arr[0][0]=67

In [34]:
arr

array([[67,  3],
       [ 3,  5]])

In [35]:
a

array([[67,  3],
       [ 3,  5]])

In [36]:
b

array([[1, 3],
       [3, 5]])

In [37]:
# arrray support slicing

In [38]:
arr[0:10]

array([[67,  3],
       [ 3,  5]])

In [39]:
arr[-1]

array([3, 5])

In [40]:
for i in arr:
    print(i)

[67  3]
[3 5]


In [41]:
np.fromfunction(lambda i,j :i == j,(4,4)) 

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [42]:
"""
   0  1   2  3 
0  T  F   F  F
 
1  F  T    F  F

2  F  F    T  F

3  F F    F   T


"""

'\n   0  1   2  3 \n0  T  F   F  F\n \n1  F  T    F  F\n\n2  F  F    T  F\n\n3  F F    F   T\n\n\n'

In [43]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
np.fromfunction(lambda i,j : i/j,(3,3)) #It handle zero division error, nan used for 0/0, inf -> 1/0

C:\Users\Delll\AppData\Local\Temp/ipykernel_8104/436498734.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j : i/j,(3,3)) #It handle zero division error, nan used for 0/0, inf -> 1/0
C:\Users\Delll\AppData\Local\Temp/ipykernel_8104/436498734.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j : i/j,(3,3)) #It handle zero division error, nan used for 0/0, inf -> 1/0


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [45]:
np.fromfunction(lambda i,j : 5*j,(3,3))

array([[ 0.,  5., 10.],
       [ 0.,  5., 10.],
       [ 0.,  5., 10.]])

In [46]:
type(i * i for i in range(5))

generator

In [47]:
[i * i for i in range(5)]

[0, 1, 4, 9, 16]

In [48]:
def test(x):
    yield x

In [49]:
test(5)

<generator object test at 0x0000025EDC623A50>

In [50]:
np.fromiter((i * i for i in range(5)), dtype= int)

array([ 0,  1,  4,  9, 16])

In [51]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [52]:
np.fromstring("1,3,4,5,", sep=',', dtype= int)

array([1, 3, 4, 5])

In [53]:
np.fromstring("11 31 41 51 ", sep=' ', dtype=int)

array([11, 31, 41, 51])

In [54]:
np.fromstring("11 31 41 51 ", sep=' ', dtype=complex)

array([11.+0.j, 31.+0.j, 41.+0.j, 51.+0.j])

In [55]:
l = [3,4,5,6,7,8]

In [56]:
arr = np.array(l)

In [57]:
arr1 =np.array([[1,2,3,4], [4,5,6,7],[1,2,3,4]])

In [58]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

In [59]:
type(arr1)

numpy.ndarray

In [60]:
type(arr)

numpy.ndarray

In [61]:
# To find the dimension of arrary
np.ndim(arr)

1

In [62]:
np.ndim(arr1)

2

In [63]:
# find total number of element inside the array
np.size(arr1)

12

In [64]:
#find out row and columns

In [65]:
np.shape(arr1) # row => 3 and columns => 4 

(3, 4)

In [66]:
arr1.dtype

dtype('int32')

In [1]:
arr1=np.array([[[12,4,45,4],[43,52,45,64],[12,45,67,86]]], dtype='<i2')

NameError: name 'np' is not defined

In [67]:
arr

array([3, 4, 5, 6, 7, 8])

In [68]:
arr.size

6

In [69]:
arr.ndim

1

In [70]:
arr.shape

(6,)

In [71]:
arr2 = np.array([[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]]])

In [72]:
arr2.ndim

3

In [73]:
arr2

array([[[1, 2, 3, 5],
        [6, 7, 8, 9]],

       [[1, 2, 3, 5],
        [6, 7, 8, 9]]])

In [74]:
arr2.size

16

In [75]:
arr2.shape

(2, 2, 4)

In [76]:
arr3 = np.array([[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]]])

In [77]:
arr3.shape # three array of size to read following 3d 

(3, 2, 4)

In [78]:
arr4 = np.array([[[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]]]])

In [79]:
arr4.shape

(1, 4, 2, 4)

In [80]:
arr4

array([[[[1, 2, 3, 5],
         [6, 7, 8, 9]],

        [[1, 2, 3, 5],
         [6, 7, 8, 9]],

        [[1, 2, 3, 5],
         [6, 7, 8, 9]],

        [[1, 2, 3, 5],
         [6, 7, 8, 9]]]])

In [81]:
arr4.ndim

4

In [82]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [83]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(6.6, dtype= int)

In [84]:
np.arange(6.6,9.8,.2)

array([6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [85]:
np.arange(6,9)

array([6, 7, 8])

In [86]:
np.arange(9,6,-.2)

array([9. , 8.8, 8.6, 8.4, 8.2, 8. , 7.8, 7.6, 7.4, 7.2, 7. , 6.8, 6.6,
       6.4, 6.2])

In [87]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [88]:
len(np.linspace(1,2))

50

In [89]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [90]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [91]:
np.linspace(5,10,5, dtype= int)

array([ 5,  6,  7,  8, 10])

In [92]:
# Generate zero data

In [93]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.zeros((2,4,4)) # 4 cross 4 in 2 matrix 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [96]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [98]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [99]:
np.empty(5)

array([ 5.,  6.,  7.,  8., 10.])

In [100]:
np.empty((3,4))

array([[1.28773832e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.37961302e-306, 1.80234778e+185, 2.81772490e+179,
        4.54585177e+174],
       [6.57701512e-038, 1.25850249e-075, 1.49136376e+161,
        1.81574593e-052]])

In [101]:
# to create matrixes

In [102]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [104]:
np.linspace(2,4,4, endpoint=False) # remove upper bound

array([2. , 2.5, 3. , 3.5])

In [105]:
np.linspace(2,4,4, endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [106]:
np.linspace([1,6],4, endpoint=False,axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [107]:
np.linspace([1,6],4, endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [108]:
np.logspace(1,2,5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [109]:
np.logspace([2],[3], axis =1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [110]:
d = np.linspace(4,7,40)

In [111]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [112]:
d.ndim

1

In [113]:
d.shape

(40,)

In [114]:
# create 2 dimension data 
# 40 row and 1 column

In [115]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [116]:
d.reshape(10,4)

array([[4.        , 4.07692308, 4.15384615, 4.23076923],
       [4.30769231, 4.38461538, 4.46153846, 4.53846154],
       [4.61538462, 4.69230769, 4.76923077, 4.84615385],
       [4.92307692, 5.        , 5.07692308, 5.15384615],
       [5.23076923, 5.30769231, 5.38461538, 5.46153846],
       [5.53846154, 5.61538462, 5.69230769, 5.76923077],
       [5.84615385, 5.92307692, 6.        , 6.07692308],
       [6.15384615, 6.23076923, 6.30769231, 6.38461538],
       [6.46153846, 6.53846154, 6.61538462, 6.69230769],
       [6.76923077, 6.84615385, 6.92307692, 7.        ]])

In [117]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [118]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [119]:
d.reshape(4,2,5)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231],
        [4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769]],

       [[4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308],
        [5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385],
        [5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923]],

       [[6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462],
        [6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [121]:
# To generate randome data

In [123]:
np.random.rand(3) # Normal distribution

array([0.36059023, 0.13314633, 0.62012256])

In [125]:
np.random.randn(5) # standard normal distribution

array([ 0.45307413, -0.18223296, -0.21748277, -0.16980788,  0.17351225])

In [126]:
np.random.randn(2,3)

array([[ 0.7914945 , -1.47019321, -0.05618954],
       [-0.56705389,  0.42587808,  0.96450736]])

In [127]:
np.random.randn(2,2,3)

array([[[-0.09537837, -1.29547788,  0.94138945],
        [ 1.31855759, -0.54292342, -1.33147271]],

       [[-0.58046382,  0.57175681,  1.35873182],
        [-0.18669759, -0.08774689, -1.36015646]]])

In [130]:
np.random.randint(50,60)

54

In [132]:
np.random.randint(5,50, (4,4))

array([[17, 20,  6, 22],
       [11, 15, 26, 38],
       [18, 26, 49, 11],
       [14, 32, 47, 35]])

In [134]:
arr = np.random.randint(5,9, (3,3))

In [135]:
arr

array([[6, 7, 6],
       [7, 8, 8],
       [7, 6, 5]])

In [137]:
arr.reshape(1,9)

array([[6, 7, 6, 7, 8, 8, 7, 6, 5]])

In [138]:
arr.reshape(9,1)

array([[6],
       [7],
       [6],
       [7],
       [8],
       [8],
       [7],
       [6],
       [5]])

In [139]:
arr.reshape(3,3)

array([[6, 7, 6],
       [7, 8, 8],
       [7, 6, 5]])

In [144]:
arr.reshape(1,3,3)

array([[[6, 7, 6],
        [7, 8, 8],
        [7, 6, 5]]])

In [145]:
arr.reshape(1,1,9)

array([[[6, 7, 6, 7, 8, 8, 7, 6, 5]]])

In [146]:
arr.reshape(3,1,3)

array([[[6, 7, 6]],

       [[7, 8, 8]],

       [[7, 6, 5]]])

In [147]:
arr.reshape(3,3,1)

array([[[6],
        [7],
        [6]],

       [[7],
        [8],
        [8]],

       [[7],
        [6],
        [5]]])

In [148]:
arr.reshape(1,9,1)

array([[[6],
        [7],
        [6],
        [7],
        [8],
        [8],
        [7],
        [6],
        [5]]])

In [151]:
arr.reshape(1,-1)

array([[6, 7, 6, 7, 8, 8, 7, 6, 5]])

In [152]:
arr.reshape(1,-12423232)

array([[6, 7, 6, 7, 8, 8, 7, 6, 5]])

In [156]:
arr.reshape(1,-1)

array([[6, 7, 6, 7, 8, 8, 7, 6, 5]])

In [149]:
arr

array([[6, 7, 6],
       [7, 8, 8],
       [7, 6, 5]])

In [150]:
arr.max()

8

In [157]:
arr.min()

5

In [158]:
arr[0]

array([6, 7, 6])

In [160]:
arr[0][0]

6

In [163]:
arr = np.random.randint(5,100, (5,5))

In [164]:
arr

array([[73, 82, 26, 92, 36],
       [48, 32, 95, 36, 44],
       [95, 97, 51, 40, 28],
       [16, 78,  7, 33, 21],
       [76, 22,  9, 90, 44]])

In [165]:
arr[3: , 3: ]

array([[33, 21],
       [90, 44]])

In [167]:
arr[0: , 3: ]

array([[92, 36],
       [36, 44],
       [40, 28],
       [33, 21],
       [90, 44]])

In [169]:
arr[0: , 0: ]

array([[73, 82, 26, 92, 36],
       [48, 32, 95, 36, 44],
       [95, 97, 51, 40, 28],
       [16, 78,  7, 33, 21],
       [76, 22,  9, 90, 44]])

In [170]:
arr[2: , 3: ]

array([[40, 28],
       [33, 21],
       [90, 44]])

In [179]:
arr[:,[1,3] ]

array([[82, 92],
       [32, 36],
       [97, 40],
       [78, 33],
       [22, 90]])

In [180]:
arr

array([[73, 82, 26, 92, 36],
       [48, 32, 95, 36, 44],
       [95, 97, 51, 40, 28],
       [16, 78,  7, 33, 21],
       [76, 22,  9, 90, 44]])

In [183]:
arr[2,[2,3]]

array([51, 40])

In [184]:
arr[[2,3],0]

array([95, 16])

In [196]:
arr[[2, 3,4], 0]

array([95, 16, 76])

In [197]:
# find the value greater than 10

In [198]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True]])

In [199]:
arr[arr>10]

array([73, 82, 26, 92, 36, 48, 32, 95, 36, 44, 95, 97, 51, 40, 28, 16, 78,
       33, 21, 76, 22, 90, 44])

In [200]:
arr * arr

array([[5329, 6724,  676, 8464, 1296],
       [2304, 1024, 9025, 1296, 1936],
       [9025, 9409, 2601, 1600,  784],
       [ 256, 6084,   49, 1089,  441],
       [5776,  484,   81, 8100, 1936]])

In [202]:
arr1 = np.random.randint(2,4, (3,3))

In [203]:
arr1

array([[3, 3, 2],
       [3, 3, 2],
       [3, 3, 2]])

In [204]:
arr2 = np.random.randint(2,4, (3,3))

In [205]:
arr2

array([[2, 3, 2],
       [3, 3, 2],
       [2, 3, 3]])

In [206]:
arr1 * arr2 # index to index multiplication

array([[6, 9, 4],
       [9, 9, 4],
       [6, 9, 6]])

In [208]:
arr1@arr2 # matrix multiplication

array([[19, 24, 18],
       [19, 24, 18],
       [19, 24, 18]])

In [209]:
arr/0 #inf means, infinity

C:\Users\Delll\AppData\Local\Temp/ipykernel_8104/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [210]:
arr**2 

array([[5329, 6724,  676, 8464, 1296],
       [2304, 1024, 9025, 1296, 1936],
       [9025, 9409, 2601, 1600,  784],
       [ 256, 6084,   49, 1089,  441],
       [5776,  484,   81, 8100, 1936]], dtype=int32)

In [211]:
# Brodcasting
# whatever we are doing with one row or column, we are doing with every row or column

In [216]:
arr = np.zeros((3,4))

In [217]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [220]:
a = np.array([1,2,3,4])

In [221]:
a 

array([1, 2, 3, 4])

In [222]:
arr + a # broadcasting for columns

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [223]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [224]:
b = np.array([5,6,7])

In [225]:
b

array([5, 6, 7])

In [228]:
b.reshape(3,1) + arr # broadcasting for columns

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [232]:
b = np.array([[5,6,7]])

In [233]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [234]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [235]:
arr = np.random.rand(5,4)

In [236]:
arr

array([[9.16318403e-01, 7.57080248e-01, 6.20463325e-01, 9.27228000e-01],
       [2.72153253e-01, 1.08724667e-01, 6.91928084e-01, 6.61835211e-01],
       [4.13036260e-01, 4.21568849e-01, 9.53742494e-01, 6.35257191e-01],
       [2.02436223e-01, 3.72248593e-01, 1.21020896e-01, 5.33382672e-06],
       [2.27292408e-01, 8.33991658e-01, 1.27952697e-01, 1.05906113e-01]])

In [237]:
np.sqrt(arr)

array([[0.95724522, 0.87010358, 0.78769494, 0.96292679],
       [0.5216831 , 0.32973424, 0.83182215, 0.81353255],
       [0.64267897, 0.64928334, 0.97659741, 0.79703023],
       [0.44992913, 0.61012179, 0.34788058, 0.00230951],
       [0.47675194, 0.91323144, 0.35770476, 0.32543219]])

In [238]:
np.exp(arr)

array([[2.50006918, 2.13204209, 1.85978953, 2.52749325],
       [1.31278817, 1.11485535, 1.99756329, 1.93834635],
       [1.51139983, 1.52435116, 2.59540479, 1.88750753],
       [1.224382  , 1.45099364, 1.1286485 , 1.00000533],
       [1.25519684, 2.30249118, 1.13649924, 1.1117175 ]])

In [239]:
np.log10(arr)

array([[-0.03795359, -0.12085808, -0.20728388, -0.03281346],
       [-0.56518647, -0.96367191, -0.15993904, -0.17925013],
       [-0.38401182, -0.37513149, -0.02056887, -0.19705041],
       [-0.69371177, -0.42916693, -0.91713963, -5.2729611 ],
       [-0.64341507, -0.07883829, -0.89295056, -0.97507897]])

In [240]:
arr1 = np.random.randint(2,5 ,(5,5))

In [241]:
arr1

array([[2, 4, 2, 3, 3],
       [2, 4, 4, 4, 4],
       [2, 3, 4, 4, 4],
       [3, 4, 2, 4, 4],
       [3, 3, 3, 2, 2]])

In [242]:
np.log10(arr1)

array([[0.30103   , 0.60205999, 0.30103   , 0.47712125, 0.47712125],
       [0.30103   , 0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.30103   , 0.47712125, 0.60205999, 0.60205999, 0.60205999],
       [0.47712125, 0.60205999, 0.30103   , 0.60205999, 0.60205999],
       [0.47712125, 0.47712125, 0.47712125, 0.30103   , 0.30103   ]])

In [245]:
np.random.seed(12) # seed method prevent to change random number
np.random.rand(2,4)

array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939],
       [0.01457496, 0.91874701, 0.90071485, 0.03342143]])