In [99]:
import numpy as np

In [100]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [101]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [102]:
np.array([1,2,"sachin",56.8])

array(['1', '2', 'sachin', '56.8'], dtype='<U32')

In [103]:
np.array([1,2,3,4,5,"sachin",4+8j])

array(['1', '2', '3', '4', '5', 'sachin', '(4+8j)'], dtype='<U64')

In [104]:
np.array([1,2,3,4,6.7])

array([1. , 2. , 3. , 4. , 6.7])

In [105]:
np.array([1,1.5,True,"sachin"])

array(['1', '1.5', 'True', 'sachin'], dtype='<U32')

In [106]:
arr1 = np.array([[3,4],[4,5]])

In [107]:
arr2= np.array([[[3,4],[4,5]]])

In [108]:
arr1

array([[3, 4],
       [4, 5]])

In [109]:
arr2

array([[[3, 4],
        [4, 5]]])

In [110]:
arr1.ndim

2

In [111]:
arr2.ndim

3

In [112]:
np.array([1,3], ndmin=2)

array([[1, 3]])

In [113]:
np.array([1,2,3,4], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [30]:
np.array([1,2,3,4], dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [31]:
np.array([4,5])

array([4, 5])

In [32]:
np.array((4,5))

array([4, 5])

In [36]:
arr = np.array([(1,2),(4,5)], dtype=[("a", '<i2'), ("b", "<i8")])

In [37]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [40]:
type(arr[0][1])

numpy.int64

In [41]:
type(arr[0][0])

numpy.int16

In [42]:
arr = np.array([[1,2],[2,4]])

In [43]:
arr

array([[1, 2],
       [2, 4]])

In [46]:
arr[0][1]

2

In [47]:
np.matrix(arr)

matrix([[1, 2],
        [2, 4]])

In [48]:
l = [1,2,3,4,5]

In [49]:
np.array(l)

array([1, 2, 3, 4, 5])

In [50]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [51]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [52]:
arr

array([[1, 2],
       [2, 4]])

In [54]:
mat=np.mat(arr)

In [55]:
mat

matrix([[1, 2],
        [2, 4]])

In [56]:
np.asanyarray(mat)

matrix([[1, 2],
        [2, 4]])

In [58]:
issubclass(np.matrix,np.ndarray)

True

In [59]:
issubclass(np.ndarray,np.matrix)

False

In [60]:
arr

array([[1, 2],
       [2, 4]])

In [72]:
arr[1:2]

array([[2, 4]])

In [73]:
arr[-1]

array([2, 4])

In [74]:
arr[1]

array([2, 4])

In [75]:
arr

array([[1, 2],
       [2, 4]])

In [76]:
arr[0]

array([1, 2])

In [77]:
arr[-0]

array([1, 2])

In [80]:
for i in arr:
    print(i)

[1 2]
[2 4]


In [82]:
np.fromfunction(lambda i, j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [90]:
np.fromfunction(lambda i, j: i*j,(4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.]])

In [89]:
np.fromfunction(lambda i, j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [93]:
type(i for i in range(5))

generator