In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.array([1,3,4,5,2, 45+6j])

array([ 1.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  2.+0.j, 45.+6.j])

In [8]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [10]:
np.array([[2,3],[3,4],[7,8,9]])

C:\Users\Delll\AppData\Local\Temp/ipykernel_10592/3249782369.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[2,3],[3,4],[7,8,9]])


array([list([2, 3]), list([3, 4]), list([7, 8, 9])], dtype=object)

In [11]:
np.array([[[2,4],[4,5],[6,8],[7,9]]])

array([[[2, 4],
        [4, 5],
        [6, 8],
        [7, 9]]])

In [12]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])

In [13]:
type(np.array([1,2,3], ndmin=3))

numpy.ndarray

In [14]:
np.array([1,2,3], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
np.array([3.2,5.3], dtype=str)

array(['3.2', '5.3'], dtype='<U3')

In [19]:
np.array([3,4], dtype=dict)

array([3, 4], dtype=object)

In [20]:
type(np.array([3,4], dtype=dict))

numpy.ndarray

In [21]:
np.array([[3,4],[5,6]])

array([[3, 4],
       [5, 6]])

In [22]:
np.array([[3,4],[5,6]], dtype=[('a', '<i2'), ('b', '<i8')])

array([[(3, 3), (4, 4)],
       [(5, 5), (6, 6)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [23]:
arr = np.array([[3,4],[5,6]], dtype=[('a', '<i2'), ('b', '<i8')])

In [27]:
arr[0][0]

(3, 3)

In [28]:
type(arr[0][0])

numpy.void

In [29]:
arr[0][1]

(4, 4)

In [30]:
arr

array([[(3, 3), (4, 4)],
       [(5, 5), (6, 6)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [31]:
type(arr[0][1])

numpy.void

In [32]:
np.array([[1,3],[4,5]])

array([[1, 3],
       [4, 5]])

In [33]:
arr = np.array([[1,3],[4,5]])

In [34]:
arr

array([[1, 3],
       [4, 5]])

In [35]:
arr[0][1]

3

In [36]:
type(arr[0][1])

numpy.int32

In [37]:
arr

array([[1, 3],
       [4, 5]])

In [38]:
np.mat(arr)

matrix([[1, 3],
        [4, 5]])

In [39]:
l = [1,3,4,5,6]

In [40]:
np.array(l)

array([1, 3, 4, 5, 6])

In [41]:
np.asarray(l)

array([1, 3, 4, 5, 6])

In [42]:
np.asanyarray(l)

array([1, 3, 4, 5, 6])

In [43]:
type(np.array(l))

numpy.ndarray

In [44]:
type(np.asarray(l))

numpy.ndarray

In [45]:
type(np.asanyarray(l))

numpy.ndarray

In [46]:
arr    

array([[1, 3],
       [4, 5]])

In [47]:
mat=np.mat(arr)

In [48]:
mat

matrix([[1, 3],
        [4, 5]])

In [49]:
np.asanyarray(mat)

matrix([[1, 3],
        [4, 5]])

In [50]:
np.array(mat)

array([[1, 3],
       [4, 5]])

In [51]:
np.asanyarray(mat)

matrix([[1, 3],
        [4, 5]])

In [52]:
issubclass(np.matrix,np.ndarray)

True

In [53]:
issubclass(np.ndarray,np.matrix)

False

In [54]:
arr

array([[1, 3],
       [4, 5]])

In [55]:
a = arr

In [56]:
b=np.copy(arr)

In [57]:
a

array([[1, 3],
       [4, 5]])

In [58]:
b

array([[1, 3],
       [4, 5]])

In [59]:
arr[0][0]

1

In [61]:
arr[0][0]=67

In [62]:
arr[0][0]

67

In [63]:
b

array([[1, 3],
       [4, 5]])

In [64]:
a

array([[67,  3],
       [ 4,  5]])

In [65]:
arr

array([[67,  3],
       [ 4,  5]])

In [66]:
arr[0:10]

array([[67,  3],
       [ 4,  5]])

In [67]:
arr[0:]

array([[67,  3],
       [ 4,  5]])

In [68]:
arr[-1]

array([4, 5])

In [69]:
arr

array([[67,  3],
       [ 4,  5]])

In [70]:
arr[1]

array([4, 5])

In [71]:
for i in arr:
    print(i)

[67  3]
[4 5]


In [73]:
np.fromfunction(lambda i, j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
np.fromfunction(lambda i,j: i/j, (5,3))

C:\Users\Delll\AppData\Local\Temp/ipykernel_10592/3593179345.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j: i/j, (5,3))
C:\Users\Delll\AppData\Local\Temp/ipykernel_10592/3593179345.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j: i/j, (5,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ],
       [inf, 3. , 1.5],
       [inf, 4. , 2. ]])

In [80]:
[i* i for i in range(5)]

[0, 1, 4, 9, 16]

In [82]:
type(i* i for i in range(5))

generator

In [85]:
def test(x):
    yield x

In [86]:
test(5)

<generator object test at 0x000001D0FEA80040>

In [91]:
np.fromiter((i * i for i in range(5)), dtype=int)

array([ 0,  1,  4,  9, 16])

In [92]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [93]:
np.fromiter((i for i in range(5)), dtype=int)

array([0, 1, 2, 3, 4])

In [101]:
np.fromstring("1,2,267,6", sep=",", dtype=int)

array([  1,   2, 267,   6])

In [102]:
np.fromstring('11,23,34,56', sep=',',dtype=complex)

array([11.+0.j, 23.+0.j, 34.+0.j, 56.+0.j])

In [103]:
l=[10,235,646,746]

In [104]:
np.array(l)

array([ 10, 235, 646, 746])

In [113]:
arr1=np.array([[[12,4,45,4],[43,52,45,64],[12,45,67,86]]])

In [114]:
arr1

array([[[12,  4, 45,  4],
        [43, 52, 45, 64],
        [12, 45, 67, 86]]])

In [107]:
type(arr1)

numpy.ndarray

In [108]:
type(arr)

numpy.ndarray

In [109]:
np.ndim(arr)

2

In [115]:
np.ndim(arr1)

3

In [116]:
np.size(arr1)

12

In [117]:
np.size(arr)

4

In [119]:
arr.dtype

dtype('int32')

In [122]:
arr1.dtype

dtype('int16')

In [121]:
arr1=np.array([[[12,4,45,4],[43,52,45,64],[12,45,67,86]]], dtype='<i2')

In [123]:
arr.size

4

In [124]:
arr1.size

12

In [125]:
arr.shape

(2, 2)

In [126]:
arr1.shape

(1, 3, 4)

In [127]:
arr1

array([[[12,  4, 45,  4],
        [43, 52, 45, 64],
        [12, 45, 67, 86]]], dtype=int16)

In [128]:
arr2=np.array([[[12,4,45,4],[43,52,45,64],[12,45,67,86]],[[12,4,45,4],[43,52,45,64],[12,45,67,86]]], dtype='<i2')

In [129]:
arr2

array([[[12,  4, 45,  4],
        [43, 52, 45, 64],
        [12, 45, 67, 86]],

       [[12,  4, 45,  4],
        [43, 52, 45, 64],
        [12, 45, 67, 86]]], dtype=int16)

In [130]:
arr2.shape

(2, 3, 4)

In [134]:
arr4 = np.array([[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]],[[1,2,3,5],[6,7,8,9]]])

In [135]:
arr4

array([[[1, 2, 3, 5],
        [6, 7, 8, 9]],

       [[1, 2, 3, 5],
        [6, 7, 8, 9]],

       [[1, 2, 3, 5],
        [6, 7, 8, 9]],

       [[1, 2, 3, 5],
        [6, 7, 8, 9]]])

In [136]:
arr4.shape

(4, 2, 4)

In [137]:
arr4.ndim

3

In [138]:
list(range(5))

[0, 1, 2, 3, 4]

##### list(range())

In [140]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [141]:
np.arange(6.6, dtype=int)

array([0, 1, 2, 3, 4, 5, 6])

In [142]:
np.arange(6.7, dtype=int)

array([0, 1, 2, 3, 4, 5, 6])

In [144]:
np.arange(6.6,9.6,.2)

array([6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4])

In [146]:
np.arange(6,9,2)

array([6, 8])

In [147]:
np.arange(19,9,-2)

array([19, 17, 15, 13, 11])

In [149]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [150]:
len(np.linspace(1,5))

50

In [155]:
np.linspace(1,5,6, dtype=int)

array([1, 1, 2, 3, 4, 5])

In [157]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
np.zeros((4,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [162]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [164]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [165]:
np.ones((4,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [167]:
np.ones((4,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [169]:
np.empty(10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [170]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [171]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [172]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [173]:
np.linspace([1,6],4, endpoint=False,axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [178]:
np.linspace([1,6],4, endpoint=False,axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [179]:
np.logspace(1,2,4)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [180]:
np.logspace(1,2,4, axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [183]:
len(np.logspace([1],[2], axis=0))

50

In [187]:
np.logspace([1],[2], axis=1)

array([[ 10.        ,  10.48113134,  10.98541142,  11.51395399,
         12.06792641,  12.64855217,  13.25711366,  13.89495494,
         14.56348478,  15.26417967,  15.9985872 ,  16.76832937,
         17.57510625,  18.42069969,  19.30697729,  20.23589648,
         21.20950888,  22.22996483,  23.29951811,  24.42053095,
         25.59547923,  26.82695795,  28.11768698,  29.47051703,
         30.88843596,  32.37457543,  33.93221772,  35.56480306,
         37.2759372 ,  39.06939937,  40.94915062,  42.9193426 ,
         44.98432669,  47.14866363,  49.41713361,  51.79474679,
         54.28675439,  56.89866029,  59.63623317,  62.50551925,
         65.51285569,  68.6648845 ,  71.9685673 ,  75.43120063,
         79.06043211,  82.86427729,  86.85113738,  91.0298178 ,
         95.40954763, 100.        ]])

In [190]:
d=np.linspace(4,7,20)

In [191]:
len(np.linspace(4,7,20))

20

In [192]:
d

array([4.        , 4.15789474, 4.31578947, 4.47368421, 4.63157895,
       4.78947368, 4.94736842, 5.10526316, 5.26315789, 5.42105263,
       5.57894737, 5.73684211, 5.89473684, 6.05263158, 6.21052632,
       6.36842105, 6.52631579, 6.68421053, 6.84210526, 7.        ])

In [193]:
d.ndim

1

In [198]:
d.reshape(10,2)

array([[4.        , 4.15789474],
       [4.31578947, 4.47368421],
       [4.63157895, 4.78947368],
       [4.94736842, 5.10526316],
       [5.26315789, 5.42105263],
       [5.57894737, 5.73684211],
       [5.89473684, 6.05263158],
       [6.21052632, 6.36842105],
       [6.52631579, 6.68421053],
       [6.84210526, 7.        ]])

In [199]:
d.reshape(5,4)

array([[4.        , 4.15789474, 4.31578947, 4.47368421],
       [4.63157895, 4.78947368, 4.94736842, 5.10526316],
       [5.26315789, 5.42105263, 5.57894737, 5.73684211],
       [5.89473684, 6.05263158, 6.21052632, 6.36842105],
       [6.52631579, 6.68421053, 6.84210526, 7.        ]])

In [205]:
d.reshape(2,2,5)

array([[[4.        , 4.15789474, 4.31578947, 4.47368421, 4.63157895],
        [4.78947368, 4.94736842, 5.10526316, 5.26315789, 5.42105263]],

       [[5.57894737, 5.73684211, 5.89473684, 6.05263158, 6.21052632],
        [6.36842105, 6.52631579, 6.68421053, 6.84210526, 7.        ]]])

In [207]:
np.random.rand(4)

array([0.38125703, 0.3881082 , 0.07706354, 0.88186207])

In [208]:
np.random.randn(5)

array([-0.18680033,  0.50694319,  0.7431109 ,  0.68454626, -1.54923684])

In [209]:
np.random.randn(2,3)

array([[-0.33951617, -0.60632076,  0.00548806],
       [-0.61309962, -0.19251925,  0.5933231 ]])

In [210]:
np.random.randint(50,60)

54

In [214]:
np.random.randint(50,90)

88

In [217]:
np.random.randint(5,50, (4,4))

array([[14, 32, 10, 39],
       [33, 10,  9, 19],
       [43, 11, 43, 18],
       [12, 28, 47, 11]])

In [219]:
arr=np.random.randint(5,9,(3,5))

In [225]:
arr.shape

(3, 5)

In [223]:
arr.reshape(1,9)

ValueError: cannot reshape array of size 15 into shape (1,9)

In [226]:
arr.reshape(3,5)

array([[6, 6, 8, 8, 5],
       [5, 8, 8, 6, 8],
       [7, 7, 5, 8, 7]])

In [228]:
arr.reshape(3,5)

array([[6, 6, 8, 8, 5],
       [5, 8, 8, 6, 8],
       [7, 7, 5, 8, 7]])

In [229]:
arr

array([[6, 6, 8, 8, 5],
       [5, 8, 8, 6, 8],
       [7, 7, 5, 8, 7]])

In [230]:
arr.max()

8

In [231]:
arr.min()

5

In [233]:
arr[0][1]

6

In [235]:
arr1=np.random.randint(5,100,(5,5))

In [236]:
arr1

array([[40, 50, 56, 24, 20],
       [96, 95, 47, 72, 34],
       [13, 58, 91, 18, 38],
       [87, 94, 63, 50, 60],
       [79, 44, 72, 93, 98]])

In [237]:
arr1.max()

98

In [238]:
arr1.min()

13

In [250]:
arr1[3:,3:]

array([[50, 60],
       [93, 98]])

In [251]:
arr1[0: , 3: ]

array([[24, 20],
       [72, 34],
       [18, 38],
       [50, 60],
       [93, 98]])

In [252]:
arr[2,[2,3]]

array([5, 8])

In [253]:
arr>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [254]:
arr

array([[6, 6, 8, 8, 5],
       [5, 8, 8, 6, 8],
       [7, 7, 5, 8, 7]])

In [255]:
arr>6

array([[False, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [ True,  True, False,  True,  True]])

In [256]:
arr[arr>6]

array([8, 8, 8, 8, 8, 7, 7, 8, 7])

In [257]:
arr * arr

array([[36, 36, 64, 64, 25],
       [25, 64, 64, 36, 64],
       [49, 49, 25, 64, 49]])

In [258]:
arr1

array([[40, 50, 56, 24, 20],
       [96, 95, 47, 72, 34],
       [13, 58, 91, 18, 38],
       [87, 94, 63, 50, 60],
       [79, 44, 72, 93, 98]])

In [259]:
a = np.array([1,2,3,4])

In [260]:
a

array([1, 2, 3, 4])

In [261]:
arr + a

ValueError: operands could not be broadcast together with shapes (3,5) (4,) 

In [262]:
b = np.array([[5,6,7]])

In [263]:
b

array([[5, 6, 7]])

In [264]:
b.T 

array([[5],
       [6],
       [7]])

In [267]:
arr = np.random.rand(5,4)

In [268]:
arr

array([[0.38721268, 0.16184591, 0.42483923, 0.47070909],
       [0.62395602, 0.59455658, 0.65348219, 0.26534794],
       [0.4949769 , 0.17700261, 0.63371327, 0.29332572],
       [0.30765234, 0.47026517, 0.17183767, 0.36575457],
       [0.69723565, 0.34246224, 0.3666056 , 0.13120449]])

In [269]:
np.sqrt(arr)

array([[0.62226416, 0.40230077, 0.65179692, 0.68608242],
       [0.78990887, 0.77107495, 0.80838245, 0.51511934],
       [0.70354595, 0.42071678, 0.7960611 , 0.54159553],
       [0.55466417, 0.68575883, 0.41453307, 0.60477647],
       [0.83500638, 0.58520274, 0.60547964, 0.36222161]])

In [270]:
np.exp(arr)

array([[1.47286971, 1.17567906, 1.52934453, 1.60112914],
       [1.86629656, 1.81222719, 1.92222274, 1.30388457],
       [1.64046035, 1.19363421, 1.88459561, 1.34087947],
       [1.36022801, 1.60041852, 1.18748505, 1.44160139],
       [2.00819369, 1.40841117, 1.44282875, 1.14020092]])

In [271]:
np.log1p(arr)

array([[0.32729647, 0.15001004, 0.35405899, 0.38574466],
       [0.48486516, 0.46659569, 0.50288348, 0.23534713],
       [0.40211076, 0.16297105, 0.4908555 , 0.25721698],
       [0.26823342, 0.38544277, 0.15857317, 0.31170708],
       [0.52900084, 0.29450542, 0.31233   , 0.12328299]])

In [272]:
arr1 = np.random.randint(2,5 ,(5,5))

In [273]:
arr1

array([[3, 2, 2, 2, 4],
       [4, 2, 2, 2, 3],
       [4, 3, 2, 4, 2],
       [2, 3, 4, 3, 2],
       [3, 3, 2, 3, 4]])

In [274]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.30103   , 0.30103   , 0.60205999],
       [0.60205999, 0.30103   , 0.30103   , 0.30103   , 0.47712125],
       [0.60205999, 0.47712125, 0.30103   , 0.60205999, 0.30103   ],
       [0.30103   , 0.47712125, 0.60205999, 0.47712125, 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   , 0.47712125, 0.60205999]])

In [275]:
np.random.seed(22)
np.random.rand(2,4)

array([[0.20846054, 0.48168106, 0.42053804, 0.859182  ],
       [0.17116155, 0.33886396, 0.27053283, 0.69104135]])