In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 6.5 kB/s 
     |████████████████████████████████| 5.8 MB 46.4 MB/s 
     |████████████████████████████████| 438 kB 53.6 MB/s 
     |████████████████████████████████| 1.6 MB 47.7 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.9.1


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
voc_size = 10000

In [12]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[9365, 88, 3276, 7081], [9365, 88, 3276, 601], [9365, 9002, 3276, 9231], [5123, 5119, 9109, 2042, 1924], [5123, 5119, 9109, 2042, 6178], [7166, 9365, 8785, 3276, 2836], [3269, 1236, 4749, 2042]]


In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [16]:
## pre padding
sent_length = 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9365   88 3276 7081]
 [   0    0    0    0 9365   88 3276  601]
 [   0    0    0    0 9365 9002 3276 9231]
 [   0    0    0 5123 5119 9109 2042 1924]
 [   0    0    0 5123 5119 9109 2042 6178]
 [   0    0    0 7166 9365 8785 3276 2836]
 [   0    0    0    0 3269 1236 4749 2042]]


In [17]:
## 10 feature dimesnions
dim=10


In [23]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')


In [24]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
##'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0, 9365,   88, 3276, 7081], dtype=int32)

In [26]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 64ms/step


array([[ 0.02254668, -0.03467371, -0.04071005,  0.04833687, -0.02766365,
        -0.03874596,  0.00580305,  0.02757757, -0.022999  , -0.03814012],
       [ 0.02254668, -0.03467371, -0.04071005,  0.04833687, -0.02766365,
        -0.03874596,  0.00580305,  0.02757757, -0.022999  , -0.03814012],
       [ 0.02254668, -0.03467371, -0.04071005,  0.04833687, -0.02766365,
        -0.03874596,  0.00580305,  0.02757757, -0.022999  , -0.03814012],
       [ 0.02254668, -0.03467371, -0.04071005,  0.04833687, -0.02766365,
        -0.03874596,  0.00580305,  0.02757757, -0.022999  , -0.03814012],
       [-0.02609651,  0.02563605,  0.0473325 ,  0.0304338 ,  0.01944745,
         0.0199814 ,  0.02515909,  0.03050848,  0.04697831, -0.01570594],
       [ 0.03394833, -0.03569539, -0.02608092,  0.03447677,  0.0188751 ,
        -0.03304424, -0.04090254, -0.01275325,  0.02098453,  0.04609554],
       [ 0.02595602,  0.02258687, -0.03916916, -0.03397846,  0.04922863,
        -0.01828157,  0.04808501, -0.02719213

In [27]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 42ms/step
[[[ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365
   -0.03874596  0.00580305  0.02757757 -0.022999   -0.03814012]
  [ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365
   -0.03874596  0.00580305  0.02757757 -0.022999   -0.03814012]
  [ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365
   -0.03874596  0.00580305  0.02757757 -0.022999   -0.03814012]
  [ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365
   -0.03874596  0.00580305  0.02757757 -0.022999   -0.03814012]
  [-0.02609651  0.02563605  0.0473325   0.0304338   0.01944745
    0.0199814   0.02515909  0.03050848  0.04697831 -0.01570594]
  [ 0.03394833 -0.03569539 -0.02608092  0.03447677  0.0188751
   -0.03304424 -0.04090254 -0.01275325  0.02098453  0.04609554]
  [ 0.02595602  0.02258687 -0.03916916 -0.03397846  0.04922863
   -0.01828157  0.04808501 -0.02719213  0.01164008 -0.04033552]
  [ 0.04146706  0.0255363   0.03406892  0.04123521 -0.028690

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 9365,   88, 3276, 7081], dtype=int32)

In [29]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 16ms/step
[[ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365 -0.03874596
   0.00580305  0.02757757 -0.022999   -0.03814012]
 [ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365 -0.03874596
   0.00580305  0.02757757 -0.022999   -0.03814012]
 [ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365 -0.03874596
   0.00580305  0.02757757 -0.022999   -0.03814012]
 [ 0.02254668 -0.03467371 -0.04071005  0.04833687 -0.02766365 -0.03874596
   0.00580305  0.02757757 -0.022999   -0.03814012]
 [-0.02609651  0.02563605  0.0473325   0.0304338   0.01944745  0.0199814
   0.02515909  0.03050848  0.04697831 -0.01570594]
 [ 0.03394833 -0.03569539 -0.02608092  0.03447677  0.0188751  -0.03304424
  -0.04090254 -0.01275325  0.02098453  0.04609554]
 [ 0.02595602  0.02258687 -0.03916916 -0.03397846  0.04922863 -0.01828157
   0.04808501 -0.02719213  0.01164008 -0.04033552]
 [ 0.04146706  0.0255363   0.03406892  0.04123521 -0.02869071 -0.0428993
 

In [31]:
### Assignment

sent1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [34]:
### Vocabulary size
voc_size1=200

In [35]:
onehot_repr1=[one_hot(words1,voc_size1)for words1 in sent1] 
print(onehot_repr1)

[[151, 120, 126, 15, 171, 127], [197, 47, 126, 43, 159, 28], [49, 160, 164, 94], [151, 198, 126, 40, 151, 150], [10, 74, 75, 126, 43, 159, 28], [191, 126, 43, 159, 96, 193]]


In [36]:
## pre padding
sent_length1=12
embedded_docs1=pad_sequences(onehot_repr1,padding='pre',maxlen=sent_length1)
print(embedded_docs1)

[[  0   0   0   0   0   0 151 120 126  15 171 127]
 [  0   0   0   0   0   0 197  47 126  43 159  28]
 [  0   0   0   0   0   0   0   0  49 160 164  94]
 [  0   0   0   0   0   0 151 198 126  40 151 150]
 [  0   0   0   0   0  10  74  75 126  43 159  28]
 [  0   0   0   0   0   0 191 126  43 159  96 193]]


In [37]:
## 10 feature dimesnions
dim=12

In [38]:
model1=Sequential()
model1.add(Embedding(voc_size1,12,input_length=sent_length1))
model1.compile('adam','mse')

In [40]:
model1.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 12, 12)            2400      
                                                                 
Total params: 2,400
Trainable params: 2,400
Non-trainable params: 0
_________________________________________________________________


In [41]:
embedded_docs1[0]

array([  0,   0,   0,   0,   0,   0, 151, 120, 126,  15, 171, 127],
      dtype=int32)

In [44]:
model1.predict(embedded_docs1[0])

1/1 [==============================] - 0s 32ms/step


array([[ 0.00969126, -0.01868799, -0.04667976,  0.04006154, -0.0122355 ,
        -0.00230545,  0.04061153,  0.04274333,  0.01704443,  0.0143596 ,
         0.02134098,  0.01044123],
       [ 0.00969126, -0.01868799, -0.04667976,  0.04006154, -0.0122355 ,
        -0.00230545,  0.04061153,  0.04274333,  0.01704443,  0.0143596 ,
         0.02134098,  0.01044123],
       [ 0.00969126, -0.01868799, -0.04667976,  0.04006154, -0.0122355 ,
        -0.00230545,  0.04061153,  0.04274333,  0.01704443,  0.0143596 ,
         0.02134098,  0.01044123],
       [ 0.00969126, -0.01868799, -0.04667976,  0.04006154, -0.0122355 ,
        -0.00230545,  0.04061153,  0.04274333,  0.01704443,  0.0143596 ,
         0.02134098,  0.01044123],
       [ 0.00969126, -0.01868799, -0.04667976,  0.04006154, -0.0122355 ,
        -0.00230545,  0.04061153,  0.04274333,  0.01704443,  0.0143596 ,
         0.02134098,  0.01044123],
       [ 0.00969126, -0.01868799, -0.04667976,  0.04006154, -0.0122355 ,
        -0.00230545,  