In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
A = np.array([
    [3,  7],
    [-4, -6],
    [7,  8],
    [1,  -1],
    [-4, -1],
    [-3, -7]
    
])

In [6]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [7]:
A.shape

(6, 2)

In [8]:
df = pd.DataFrame(A, columns=['a0','a1'])

In [9]:
df

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [10]:
a0 = A[:,0]
a1 = A[:,1]

In [11]:
np.cov(a0,a1)

array([[20., 25.],
       [25., 40.]])

In [14]:
A.T @ A/5

array([[20., 25.],
       [25., 40.]])

In [15]:
sigma = A.T @ A/5